"""empty message

Revision ID: 07740c8a7f71
Revises: 08ba1538285d
Create Date: 2026-09-01 07:10:05.298521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07740c8a7f71'
down_revision: Union[str, Sequence[str], None] = '08ba1538285d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('loans', sa.Column('payment_submitted_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('loans', 'paid_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('paid_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('loans', 'payment_submitted_date')
    op.drop_column('loans', 'payment_status')
    # ### end Alembic commands ###
