"""add renewal_count to loan

Revision ID: 0b8a4fd8a7f8
Revises: 72764954419c
Create Date: 2026-08-29 22:38:44.149208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b8a4fd8a7f8'
down_revision: Union[str, Sequence[str], None] = '72764954419c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('renewal_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'renewal_count')
    # ### end Alembic commands ###
