"""add fine_amount to loans

Revision ID: 67ad67340017
Revises: 0b8a4fd8a7f8
Create Date: 2026-08-30 23:31:57.640341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ad67340017'
down_revision: Union[str, Sequence[str], None] = '0b8a4fd8a7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('fine_amount', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'fine_amount')
    # ### end Alembic commands ###
